---

- name: Find out if it is baremetal or vm
  command: "systemd-detect-virt"
  register: virt
  ignore_errors: true

- name: 'PREREQUISITES | prerequisites nginx'
  import_tasks: "prerequisites.yml"
  tags: ['nginx', 'nginx::prerequisites']

- name: 'INSTALL | install nginx'
  import_tasks: "install.yml"
  tags: ['nginx', 'nginx::install']

- name: 'CONFIG | config nginx'
  import_tasks: "config.yml"
  tags: ['nginx', 'nginx::config']

